apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  steps:
    - name: install-dependencies
      image: python:3.10
      script: |
        pip install -r app/requirements.txt
        pip install nose

    - name: run-tests
      image: python:3.10
      script: |
        nosetests -v

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: clean
      image: alpine
      script: |
        echo "Cleaning workspace"
